const express = require('express');
const { authenticateToken } = require('../middleware/auth');
const {
  cancelRenewal,
  updatePaymentMethod,
} = require('../controllers/subscriptionManagementController');

const router = express.Router();

// Endpoint for canceling automatic renewal. A PUT is used to express that
// the resource (subscription) is being updated. The path uses
// "assinaturas" to keep the naming consistent with the Portuguese API
// semantics used in the frontend.
router.put('/assinaturas/cancelar-renovacao', authenticateToken, cancelRenewal);

// Endpoint for updating the payment method of a subscription. Receives a
// `cardToken` generated by Mercado Pago.js on the frontend and forwards it
// to the Mercado Pago API. The user must be authenticated to modify their
// own subscription.
router.put('/assinaturas/atualizar-pagamento', authenticateToken, updatePaymentMethod);

module.exports = router;